/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.biblioteca.biblioteca.vistas;

/**
 *
 * @author debian-andrey
 */
public class JFLibros extends javax.swing.JFrame {

    /**
     * Creates new form JFLibros
     */
    public void main(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }
    public JFLibros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLibros = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cmbEditoriales = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbTematica = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rExistenteAutor = new javax.swing.JRadioButton();
        rNuevoAutor = new javax.swing.JRadioButton();
        Autores = new javax.swing.JLabel();
        cmbAutores = new javax.swing.JComboBox<>();
        txtAutorNombre = new javax.swing.JTextField();
        rNuevoEditorial = new javax.swing.JRadioButton();
        rExistenteEditorial = new javax.swing.JRadioButton();
        rNuevoTematica = new javax.swing.JRadioButton();
        rExistenteTematica = new javax.swing.JRadioButton();
        txtTematica = new javax.swing.JTextField();
        txtEditoial = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        txtAutorA2 = new javax.swing.JTextField();
        txtAutorA1 = new javax.swing.JTextField();
        lblApellido2 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblApellido1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputFecha = new com.github.lgooddatepicker.components.DatePicker();
        jPanel2 = new javax.swing.JPanel();
        app_Tittle = new javax.swing.JLabel();
        btn_atras = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "ISBN", "Fecha", "Precio", "Autor", "Editorial", "Tematica"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableLibros);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 607, 169));

        jLabel4.setText("Editoriales");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        cmbEditoriales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbEditoriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 150, -1));

        jLabel5.setText("Tematica");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, -1, -1));

        cmbTematica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 150, -1));

        jLabel1.setText("Titulo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 108, 27));

        jLabel2.setText("ISBN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));
        jPanel1.add(txtISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 112, 27));
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 112, 27));

        jLabel3.setText("Fecha");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, -1, -1));

        rExistenteAutor.setText("Existente");
        jPanel1.add(rExistenteAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        rNuevoAutor.setSelected(true);
        rNuevoAutor.setText("Nuevo");
        jPanel1.add(rNuevoAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        Autores.setText("Autor");
        jPanel1.add(Autores, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, 9));

        cmbAutores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 150, -1));
        jPanel1.add(txtAutorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 150, 27));

        rNuevoEditorial.setSelected(true);
        rNuevoEditorial.setText("Nuevo");
        jPanel1.add(rNuevoEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        rExistenteEditorial.setText("Existente");
        jPanel1.add(rExistenteEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        rNuevoTematica.setSelected(true);
        rNuevoTematica.setText("Nuevo");
        jPanel1.add(rNuevoTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, -1, -1));

        rExistenteTematica.setText("Existente");
        jPanel1.add(rExistenteTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, -1, -1));
        jPanel1.add(txtTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 150, 27));
        jPanel1.add(txtEditoial, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 150, 27));

        btnAgregar.setText("Agregar");
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 210, -1));
        jPanel1.add(txtAutorA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 150, 27));
        jPanel1.add(txtAutorA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 150, 27));

        lblApellido2.setText("Apellido2");
        lblApellido2.setToolTipText("");
        jPanel1.add(lblApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        lblNombre1.setText("Nombre");
        lblNombre1.setToolTipText("");
        jPanel1.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        lblApellido1.setText("Apellido1");
        lblApellido1.setToolTipText("");
        jPanel1.add(lblApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jLabel6.setText("Precio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));
        jPanel1.add(inputFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, -1, -1));

        jPanel2.setBackground(new java.awt.Color(130, 204, 171));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        app_Tittle.setBackground(new java.awt.Color(255, 255, 255));
        app_Tittle.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 22)); // NOI18N
        app_Tittle.setForeground(new java.awt.Color(255, 255, 255));
        app_Tittle.setText("Sección: Registro de libro");
        jPanel2.add(app_Tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 270, 50));

        btn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Go_Back_35px.png"))); // NOI18N
        jPanel2.add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Add_Book_35px.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 50, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 50));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Autores;
    private javax.swing.JLabel app_Tittle;
    public javax.swing.JButton btnAgregar;
    private javax.swing.JLabel btn_atras;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> cmbAutores;
    public javax.swing.JComboBox<String> cmbEditoriales;
    public javax.swing.JComboBox<String> cmbTematica;
    public com.github.lgooddatepicker.components.DatePicker inputFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblApellido1;
    public javax.swing.JLabel lblApellido2;
    public javax.swing.JLabel lblNombre1;
    public javax.swing.JRadioButton rExistenteAutor;
    public javax.swing.JRadioButton rExistenteEditorial;
    public javax.swing.JRadioButton rExistenteTematica;
    public javax.swing.JRadioButton rNuevoAutor;
    public javax.swing.JRadioButton rNuevoEditorial;
    public javax.swing.JRadioButton rNuevoTematica;
    public javax.swing.JTable tableLibros;
    public javax.swing.JTextField txtAutorA1;
    public javax.swing.JTextField txtAutorA2;
    public javax.swing.JTextField txtAutorNombre;
    public javax.swing.JTextField txtEditoial;
    public javax.swing.JTextField txtISBN;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtTematica;
    public javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
