/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.biblioteca.biblioteca.vistas;

/**
 *
 * @author debian-andrey
 */
public class JFLibros extends javax.swing.JFrame {

    /**
     * Creates new form JFLibros
     */
    public void main() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    public JFLibros() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(1338, 760);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLibros = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cmbEditoriales = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbTematica = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rExistenteAutor = new javax.swing.JRadioButton();
        rNuevoAutor = new javax.swing.JRadioButton();
        Autores = new javax.swing.JLabel();
        cmbAutores = new javax.swing.JComboBox<>();
        txtAutorNombre = new javax.swing.JTextField();
        rNuevoEditorial = new javax.swing.JRadioButton();
        rExistenteEditorial = new javax.swing.JRadioButton();
        rNuevoTematica = new javax.swing.JRadioButton();
        rExistenteTematica = new javax.swing.JRadioButton();
        txtTematica = new javax.swing.JTextField();
        txtEditoial = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        txtAutorA2 = new javax.swing.JTextField();
        txtAutorA1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputFecha = new com.github.lgooddatepicker.components.DatePicker();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        app_Tittle = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblCmbTematica = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        lblTxtTematica = new javax.swing.JLabel();
        lblCmbEditorial = new javax.swing.JLabel();
        lblAutorNuevo = new javax.swing.JLabel();
        lblTxtEditorial = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        separadorEditorial = new javax.swing.JSeparator();
        separadorTematica = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        panelAutor = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblApellido1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblApellido2 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnregreso = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(130, 204, 171));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableLibros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 204, 171), 3));
        tableLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "ISBN", "Fecha", "Precio", "Autor", "Editorial", "Tematica"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableLibros);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 1090, 180));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Versions_55px.png"))); // NOI18N
        jLabel4.setText("Editoriales:");
        jLabel4.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 170, -1));

        cmbEditoriales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEditoriales.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jPanel1.add(cmbEditoriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 160, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Comments_55px.png"))); // NOI18N
        jLabel5.setText("Temática:");
        jLabel5.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 220, 150, -1));

        cmbTematica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTematica.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jPanel1.add(cmbTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 370, 160, -1));

        jLabel1.setText("Título:");
        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 50, 50));

        txtTitulo.setBorder(null);
        txtTitulo.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 210, 30));

        jLabel2.setText("ISBN:");
        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 50, 50));

        txtISBN.setBorder(null);
        txtISBN.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jPanel1.add(txtISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 210, 30));

        txtPrecio.setBorder(null);
        txtPrecio.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 210, 30));

        jLabel3.setText("Fecha:");
        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 90, 60, 50));

        rExistenteAutor.setText("Existente");
        rExistenteAutor.setBackground(new java.awt.Color(255, 255, 255));
        rExistenteAutor.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jPanel1.add(rExistenteAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        rNuevoAutor.setSelected(true);
        rNuevoAutor.setText("Nuevo");
        rNuevoAutor.setBackground(new java.awt.Color(255, 255, 255));
        rNuevoAutor.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jPanel1.add(rNuevoAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        Autores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Edit_Property_55px.png"))); // NOI18N
        Autores.setText("Autor:");
        Autores.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        jPanel1.add(Autores, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 140, 60));

        cmbAutores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAutores.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jPanel1.add(cmbAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 150, -1));

        txtAutorNombre.setBorder(null);
        txtAutorNombre.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jPanel1.add(txtAutorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 150, 27));

        rNuevoEditorial.setSelected(true);
        rNuevoEditorial.setText("Nuevo");
        rNuevoEditorial.setBackground(new java.awt.Color(255, 255, 255));
        rNuevoEditorial.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jPanel1.add(rNuevoEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, -1));

        rExistenteEditorial.setText("Existente");
        rExistenteEditorial.setBackground(new java.awt.Color(255, 255, 255));
        rExistenteEditorial.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jPanel1.add(rExistenteEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, -1, -1));

        rNuevoTematica.setSelected(true);
        rNuevoTematica.setText("Nuevo");
        rNuevoTematica.setBackground(new java.awt.Color(255, 255, 255));
        rNuevoTematica.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jPanel1.add(rNuevoTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 290, -1, -1));

        rExistenteTematica.setText("Existente");
        rExistenteTematica.setBackground(new java.awt.Color(255, 255, 255));
        rExistenteTematica.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jPanel1.add(rExistenteTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 290, -1, -1));

        txtTematica.setBorder(null);
        txtTematica.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jPanel1.add(txtTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 330, 160, 27));

        txtEditoial.setBorder(null);
        txtEditoial.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jPanel1.add(txtEditoial, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 160, 27));

        btnAgregar.setText("Agregar");
        btnAgregar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 290, 50));

        txtAutorA2.setBorder(null);
        txtAutorA2.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jPanel1.add(txtAutorA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 410, 150, 27));

        txtAutorA1.setBorder(null);
        txtAutorA1.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jPanel1.add(txtAutorA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 370, 150, 27));

        jLabel6.setText("Precio:");
        jLabel6.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 60, 50));
        jPanel1.add(inputFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 100, 240, 30));

        jPanel2.setBackground(new java.awt.Color(130, 204, 171));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Add_55px.png"))); // NOI18N
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 60, 60));

        app_Tittle.setText("Registro bibliotecario");
        app_Tittle.setBackground(new java.awt.Color(255, 255, 255));
        app_Tittle.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 30)); // NOI18N
        jPanel2.add(app_Tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 320, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Pay_Date_35px.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 90, 40, 50));

        lblCmbTematica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Bulleted_List_35px.png"))); // NOI18N
        jPanel1.add(lblCmbTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 360, 40, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Pin_Code_35px.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 40, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Paper_Money_35px.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 40, 50));

        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 204, 171), 3));
        jSeparator3.setForeground(new java.awt.Color(130, 204, 171));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 350, 230));

        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 204, 171), 3));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 350, 140));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Title_35px_1.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 40, 50));

        lblTxtTematica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Name_Tag_35px.png"))); // NOI18N
        jPanel1.add(lblTxtTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, 40, 50));

        lblCmbEditorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Bulleted_List_35px.png"))); // NOI18N
        jPanel1.add(lblCmbEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 40, 40));

        lblAutorNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Bulleted_List_35px.png"))); // NOI18N
        jPanel1.add(lblAutorNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 40, 50));

        lblTxtEditorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Name_Tag_35px.png"))); // NOI18N
        jPanel1.add(lblTxtEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 40, 50));

        jSeparator5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 204, 171), 3));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, 300, 140));
        jPanel1.add(separadorEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 160, 10));
        jPanel1.add(separadorTematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 360, 160, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 160, 10));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 210, 10));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 360, 160, 10));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 210, 10));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 210, 10));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Name_Tag_35px.png"))); // NOI18N

        lblNombre1.setText("Nombre:");
        lblNombre1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        lblNombre1.setToolTipText("");

        lblApellido1.setText("Primer apellido:");
        lblApellido1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        lblApellido1.setToolTipText("");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Name_Tag_35px.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Name_Tag_35px.png"))); // NOI18N

        lblApellido2.setText("Segundo apellido:");
        lblApellido2.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        lblApellido2.setToolTipText("");

        javax.swing.GroupLayout panelAutorLayout = new javax.swing.GroupLayout(panelAutor);
        panelAutor.setLayout(panelAutorLayout);
        panelAutorLayout.setHorizontalGroup(
            panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAutorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAutorLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblNombre1))
                    .addGroup(panelAutorLayout.createSequentialGroup()
                        .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAutorLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblApellido1)
                            .addGroup(panelAutorLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblApellido2)
                            .addGroup(panelAutorLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelAutorLayout.setVerticalGroup(
            panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutorLayout.createSequentialGroup()
                .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAutorLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblNombre1)))
                .addGroup(panelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAutorLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAutorLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblApellido2)
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(panelAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 310, -1, -1));

        btnregreso.setText("Regresar al menu principal");
        btnregreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresoActionPerformed(evt);
            }
        });
        jPanel1.add(btnregreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 600, -1, -1));

        btnEditar.setText("Editar");
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 550, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresoActionPerformed

        JFMenuPrincipal m = new JFMenuPrincipal();
        m.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnregresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Autores;
    private javax.swing.JLabel app_Tittle;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnregreso;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> cmbAutores;
    public javax.swing.JComboBox<String> cmbEditoriales;
    public javax.swing.JComboBox<String> cmbTematica;
    public com.github.lgooddatepicker.components.DatePicker inputFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JLabel lblApellido1;
    public javax.swing.JLabel lblApellido2;
    public javax.swing.JLabel lblAutorNuevo;
    public javax.swing.JLabel lblCmbEditorial;
    public javax.swing.JLabel lblCmbTematica;
    public javax.swing.JLabel lblNombre1;
    public javax.swing.JLabel lblTxtEditorial;
    public javax.swing.JLabel lblTxtTematica;
    public javax.swing.JPanel panelAutor;
    public javax.swing.JRadioButton rExistenteAutor;
    public javax.swing.JRadioButton rExistenteEditorial;
    public javax.swing.JRadioButton rExistenteTematica;
    public javax.swing.JRadioButton rNuevoAutor;
    public javax.swing.JRadioButton rNuevoEditorial;
    public javax.swing.JRadioButton rNuevoTematica;
    public javax.swing.JSeparator separadorEditorial;
    public javax.swing.JSeparator separadorTematica;
    public javax.swing.JTable tableLibros;
    public javax.swing.JTextField txtAutorA1;
    public javax.swing.JTextField txtAutorA2;
    public javax.swing.JTextField txtAutorNombre;
    public javax.swing.JTextField txtEditoial;
    public javax.swing.JTextField txtISBN;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtTematica;
    public javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
