/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.biblioteca.biblioteca.vistas;

import com.biblioteca.biblioteca.controladores.LibroController;
import com.biblioteca.biblioteca.controladores.RegisterController;
import com.biblioteca.biblioteca.modelos.PersonaDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author cesar
 */
public class JFMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public JFMenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Devoluciones = new javax.swing.JPanel();
        app_Tittle = new javax.swing.JLabel();
        btn_RegistroBibliotecario = new javax.swing.JPanel();
        app_Tittle1 = new javax.swing.JLabel();
        btn_Búsqueda = new javax.swing.JPanel();
        app_Tittle2 = new javax.swing.JLabel();
        btn_Libro = new javax.swing.JPanel();
        app_Tittle3 = new javax.swing.JLabel();
        btnRegistroBibliotecario = new javax.swing.JPanel();
        app_Tittle4 = new javax.swing.JLabel();
        btn_Inventario = new javax.swing.JPanel();
        app_Tittle5 = new javax.swing.JLabel();
        app_Tittle6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Devoluciones.setBackground(new java.awt.Color(130, 204, 171));
        btn_Devoluciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_Devoluciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DevolucionesMouseClicked(evt);
            }
        });

        app_Tittle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Assignment_Return_50px.png"))); // NOI18N
        app_Tittle.setText("Devoluciones");
        app_Tittle.setBackground(new java.awt.Color(255, 255, 255));
        app_Tittle.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N

        javax.swing.GroupLayout btn_DevolucionesLayout = new javax.swing.GroupLayout(btn_Devoluciones);
        btn_Devoluciones.setLayout(btn_DevolucionesLayout);
        btn_DevolucionesLayout.setHorizontalGroup(
            btn_DevolucionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_DevolucionesLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(app_Tittle)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        btn_DevolucionesLayout.setVerticalGroup(
            btn_DevolucionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(app_Tittle, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel1.add(btn_Devoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 350, 70));

        btn_RegistroBibliotecario.setBackground(new java.awt.Color(130, 204, 171));
        btn_RegistroBibliotecario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        app_Tittle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Check_50px.png"))); // NOI18N
        app_Tittle1.setText("En Proceso...");
        app_Tittle1.setBackground(new java.awt.Color(255, 255, 255));
        app_Tittle1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        app_Tittle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                app_Tittle1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_RegistroBibliotecarioLayout = new javax.swing.GroupLayout(btn_RegistroBibliotecario);
        btn_RegistroBibliotecario.setLayout(btn_RegistroBibliotecarioLayout);
        btn_RegistroBibliotecarioLayout.setHorizontalGroup(
            btn_RegistroBibliotecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_RegistroBibliotecarioLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(app_Tittle1)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        btn_RegistroBibliotecarioLayout.setVerticalGroup(
            btn_RegistroBibliotecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(app_Tittle1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel1.add(btn_RegistroBibliotecario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 350, 70));

        btn_Búsqueda.setBackground(new java.awt.Color(130, 204, 171));
        btn_Búsqueda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_Búsqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BúsquedaMouseClicked(evt);
            }
        });

        app_Tittle2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Search_50px.png"))); // NOI18N
        app_Tittle2.setText("Búsqueda");
        app_Tittle2.setBackground(new java.awt.Color(255, 255, 255));
        app_Tittle2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N

        javax.swing.GroupLayout btn_BúsquedaLayout = new javax.swing.GroupLayout(btn_Búsqueda);
        btn_Búsqueda.setLayout(btn_BúsquedaLayout);
        btn_BúsquedaLayout.setHorizontalGroup(
            btn_BúsquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_BúsquedaLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(app_Tittle2)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        btn_BúsquedaLayout.setVerticalGroup(
            btn_BúsquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(app_Tittle2, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel1.add(btn_Búsqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 350, 70));

        btn_Libro.setBackground(new java.awt.Color(130, 204, 171));
        btn_Libro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_Libro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LibroMouseClicked(evt);
            }
        });

        app_Tittle3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Book_52px.png"))); // NOI18N
        app_Tittle3.setText("Libros");
        app_Tittle3.setBackground(new java.awt.Color(255, 255, 255));
        app_Tittle3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N

        javax.swing.GroupLayout btn_LibroLayout = new javax.swing.GroupLayout(btn_Libro);
        btn_Libro.setLayout(btn_LibroLayout);
        btn_LibroLayout.setHorizontalGroup(
            btn_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_LibroLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(app_Tittle3)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        btn_LibroLayout.setVerticalGroup(
            btn_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(app_Tittle3, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel1.add(btn_Libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 350, 70));

        btnRegistroBibliotecario.setBackground(new java.awt.Color(130, 204, 171));
        btnRegistroBibliotecario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegistroBibliotecario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroBibliotecarioMouseClicked(evt);
            }
        });

        app_Tittle4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Add_50px.png"))); // NOI18N
        app_Tittle4.setText("Registro Bibliotecario");
        app_Tittle4.setBackground(new java.awt.Color(255, 255, 255));
        app_Tittle4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        app_Tittle4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                app_Tittle4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnRegistroBibliotecarioLayout = new javax.swing.GroupLayout(btnRegistroBibliotecario);
        btnRegistroBibliotecario.setLayout(btnRegistroBibliotecarioLayout);
        btnRegistroBibliotecarioLayout.setHorizontalGroup(
            btnRegistroBibliotecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegistroBibliotecarioLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(app_Tittle4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnRegistroBibliotecarioLayout.setVerticalGroup(
            btnRegistroBibliotecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(app_Tittle4, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel1.add(btnRegistroBibliotecario, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 350, 70));

        btn_Inventario.setBackground(new java.awt.Color(130, 204, 171));
        btn_Inventario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_Inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_InventarioMouseClicked(evt);
            }
        });

        app_Tittle5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Scan_Stock_50px.png"))); // NOI18N
        app_Tittle5.setText("Inventario");
        app_Tittle5.setBackground(new java.awt.Color(255, 255, 255));
        app_Tittle5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N

        javax.swing.GroupLayout btn_InventarioLayout = new javax.swing.GroupLayout(btn_Inventario);
        btn_Inventario.setLayout(btn_InventarioLayout);
        btn_InventarioLayout.setHorizontalGroup(
            btn_InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_InventarioLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(app_Tittle5)
                .addGap(93, 93, 93))
        );
        btn_InventarioLayout.setVerticalGroup(
            btn_InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(app_Tittle5, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel1.add(btn_Inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 350, 70));

        app_Tittle6.setBackground(new java.awt.Color(255, 255, 255));
        app_Tittle6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 30)); // NOI18N
        app_Tittle6.setText("Menú Principal");
        jPanel1.add(app_Tittle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 220, 40));

        jSeparator1.setBackground(new java.awt.Color(130, 204, 171));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 220, 30));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Sign_Out_48px.png"))); // NOI18N
        jLabel1.setText("Cerrar Sesión");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 200, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void app_Tittle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_app_Tittle1MouseClicked


    }//GEN-LAST:event_app_Tittle1MouseClicked

    private void btn_LibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LibroMouseClicked

        try {
            LibroController lconController = new LibroController();
        } catch (SQLException ex) {
            System.out.println(";c");
        }


    }//GEN-LAST:event_btn_LibroMouseClicked

    private void btn_DevolucionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DevolucionesMouseClicked

        JFDevoluciones d = new JFDevoluciones();
        d.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_btn_DevolucionesMouseClicked

    private void btnRegistroBibliotecarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroBibliotecarioMouseClicked
        JFRegister r = new JFRegister();
        PersonaDAO personaDAO = new PersonaDAO();
        try {
            RegisterController rc = new RegisterController(r, personaDAO);
        } catch (SQLException ex) {
            Logger.getLogger(JFMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistroBibliotecarioMouseClicked

    private void btn_InventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InventarioMouseClicked

        Inventario i = new Inventario();
        i.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_btn_InventarioMouseClicked

    private void btn_BúsquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BúsquedaMouseClicked

        JFBusqueda b = new JFBusqueda();
        b.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_BúsquedaMouseClicked

    private void app_Tittle4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_app_Tittle4MouseClicked

        JFRegister jf = new JFRegister();
        jf.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_app_Tittle4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel app_Tittle;
    private javax.swing.JLabel app_Tittle1;
    private javax.swing.JLabel app_Tittle2;
    private javax.swing.JLabel app_Tittle3;
    private javax.swing.JLabel app_Tittle4;
    private javax.swing.JLabel app_Tittle5;
    private javax.swing.JLabel app_Tittle6;
    private javax.swing.JPanel btnRegistroBibliotecario;
    private javax.swing.JPanel btn_Búsqueda;
    private javax.swing.JPanel btn_Devoluciones;
    private javax.swing.JPanel btn_Inventario;
    private javax.swing.JPanel btn_Libro;
    private javax.swing.JPanel btn_RegistroBibliotecario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
